vllm: unify environment variable LLM_MODEL_ID
opea-project/GenAIComps pull request #1089
Opened 2024-12-30 03:15 UTC by lianhao

## Description

Currently, vllm services use the environment variable `LLM_MODEL` while all other services in llm category are using `LLM_MODEL_ID`. This PR unify all the services in llm category to use the same environment variable `LLM_MODEL_ID` to minimize the configuration management efforts such as docker-compose, helm, etc.

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-12-30 12:22 UTC, eero-t requested changes
This replaces only first instance of LLM_MODEL in each file, but several of the files contain multiple instances of it:
```
$ git grep -c [^_]LLM_MODEL[:=]
comps/llms/text-generation/README.md:5
comps/llms/text-generation/vllm/langchain/README.md:1
comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:2
comps/llms/text-generation/vllm/langchain/launch_microservice.sh:1
comps/llms/text-generation/vllm/llama_index/README.md:1
comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:2
comps/llms/text-generation/vllm/llama_index/launch_microservice.sh:1
tests/llms/test_llms_text-generation_vllm_langchain_on_intel_hpu.sh:2
tests/llms/test_llms_text-generation_vllm_llamaindex_on_intel_hpu.sh:2
```

2024-12-30 12:39 UTC, eero-t commented
PRs containing workarounds for the bug this PR will fix:
* https://github.com/opea-project/GenAIInfra/pull/649
* https://github.com/opea-project/GenAIInfra/pull/659

2024-12-31 02:26 UTC, lianhao commented
> This PR replaces only first instance of LLM_MODEL in each file, but several of the files contain multiple instances of it:
> 
> ```
> $ git grep -c [^_]LLM_MODEL[:=]
> comps/llms/text-generation/README.md:5
> comps/llms/text-generation/vllm/langchain/README.md:1
> comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:2
> comps/llms/text-generation/vllm/langchain/launch_microservice.sh:1
> comps/llms/text-generation/vllm/llama_index/README.md:1
> comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:2
> comps/llms/text-generation/vllm/llama_index/launch_microservice.sh:1
> tests/llms/test_llms_text-generation_vllm_langchain_on_intel_hpu.sh:2
> tests/llms/test_llms_text-generation_vllm_llamaindex_on_intel_hpu.sh:2
> ```
Already double checked, the remaining are bash environment variables, which are used by both tgi/vllm and llm-docsum-tgi/vllm. This `LLM_MODEL` bash environment variables will be passed to llm-docsum-xxx container using `-e LLM_MODEL_ID=${LLM_MODEL}` in all the readme and test scripts, just as what this PR has already done.

2024-12-31 02:30 UTC, lianhao commented
> This PR replaces only first instance of LLM_MODEL in each file, but several of the files contain multiple instances of it:
> 
> ```
> $ git grep -c [^_]LLM_MODEL[:=]
> comps/llms/text-generation/README.md:5
> comps/llms/text-generation/vllm/langchain/README.md:1
> comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:2
> comps/llms/text-generation/vllm/langchain/launch_microservice.sh:1
> comps/llms/text-generation/vllm/llama_index/README.md:1
> comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:2
> comps/llms/text-generation/vllm/llama_index/launch_microservice.sh:1
> tests/llms/test_llms_text-generation_vllm_langchain_on_intel_hpu.sh:2
> tests/llms/test_llms_text-generation_vllm_llamaindex_on_intel_hpu.sh:2
> ```

Already double checked, the remaining bash environment variable `LLM_MODEL`, which are used by upstream tgi/vllm, not the llm-vllm services this PR is trying to modify.

2024-12-31 12:27 UTC, eero-t commented
These are not Bash `export`s:
```
$ git grep  [^_]LLM_MODEL[:=] | grep compose
comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
```

PR changes only first of those?

2025-01-02 02:03 UTC, lianhao commented
> These are not Bash `export`s:
> 
> ```
> $ git grep  [^_]LLM_MODEL[:=] | grep compose
> comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> ```
> 
> PR changes only first of those?

Yes, the remaining `LLM_MODEL` is not for llm-vllm wrapper container, but for the vllm itself(which is a opea rebuild of upstream vllm).

2025-01-02 03:06 UTC, xiguiw commented
> > These are not Bash `export`s:
> > ```
> > $ git grep  [^_]LLM_MODEL[:=] | grep compose
> > comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> > comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> > comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> > comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml:      LLM_MODEL: ${LLM_MODEL}
> > ```


> >   
> > PR changes only first of those?
> 
> Yes, the remaining `LLM_MODEL` is not for llm-vllm wrapper container, but for the vllm itself(which is a opea rebuild of upstream vllm).

@lianhao 
Greate! This is helpful. It makes things simple.
Do you know the status of TEI_MODEL and RERANKING MODLEL environment variables?  Do you plan to unify them?
Thanks!

2025-01-02 05:49 UTC, lianhao commented
> Do you know the status of TEI_MODEL and RERANKING MODLEL environment variables? Do you plan to unify them?
> Thanks!

Sorry, I'm not aware of that

2025-01-02 12:15 UTC, eero-t commented
>> These are not Bash `export`s:
>> ...
>> PR changes only first of those?
> 
> Yes, the remaining `LLM_MODEL` is not for llm-vllm wrapper container, but for the vllm itself(which is a opea rebuild of upstream vllm).

Sure, but it's given to vLLM with `--model` option, so it could be changed also.   Usage of multiple env var names for the same purpose in same file is confusing.  Why not change all of them?

2025-01-15 10:20 UTC, lianhao commented
closed as new llm-textgen doesn't have this issue

2025-01-15 10:20 UTC, closed without merging