Refactor rerank
opea-project/GenAIComps pull request #1095
Opened 2024-12-31 06:36 UTC by WenjiaoYue

## Description

Refactor the video rerank and overall structure.

## Issues

 `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

no

## Tests

CI pass.

2024-12-31 07:09 UTC, ZePan110 commented
Remove commit a6091e8 before merging after testing is completed

2024-12-31 09:33 UTC, xiguiw commented
@WenjiaoYue @ZePan110 
https://github.com/opea-project/GenAIExamples/pull/1325 depending on this PR.
Please help to resolve the dependency. 
Thanks!

2025-01-01 04:49 UTC, chensuyue commented on tests/rerankings/test_rerankings_opea_tei.sh
> +    docker run -d --name="test-comps-reranking-tei-server" -e LOGFLAG=True  -p ${tei_service_port}:8000 --ipc=host -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e TEI_RERANKING_ENDPOINT=$TEI
Test image tag keep `comps`.

2025-01-01 04:50 UTC, chensuyue commented on .github/workflows/docker/compose/reranks-compose.yaml
>  services:
yaml name should also be renamed.

2025-01-02 02:53 UTC, WenjiaoYue commented on tests/rerankings/test_rerankings_opea_tei.sh
> +    docker run -d --name="test-comps-reranking-tei-server" -e LOGFLAG=True  -p ${tei_service_port}:8000 --ipc=host -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e TEI_RERANKING_ENDPOINT=$TEI
Done.

2025-01-02 02:53 UTC, WenjiaoYue commented on .github/workflows/docker/compose/reranks-compose.yaml
>  services:
Done, waiting for 1072 merge.

2025-01-02 03:03 UTC, lkk12014402 approved these changes
LGTM

2025-01-02 03:06 UTC, ZePan110 approved these changes

2025-01-02 03:25 UTC, chensuyue commented
Please DO NOT merge this one.

2025-01-02 03:29 UTC, chensuyue commented
> @WenjiaoYue @ZePan110 [opea-project/GenAIExamples#1325](https://github.com/opea-project/GenAIExamples/pull/1325) depending on this PR. Please help to resolve the dependency. Thanks!

The Examples PR need to update all the place related to this PR, changes in #1325 is not full coverage.

2025-01-02 07:44 UTC, xiguiw requested changes

2025-01-02 07:44 UTC, xiguiw commented on comps/rerankings/deployment/docker_compose/rerank_tei.yaml
RERANK_TYPE: tei

2025-01-02 07:44 UTC, xiguiw commented on comps/rerankings/deployment/docker_compose/rerank_tei.yaml
>      ports:
line 32, environment add

RERANK_TYPE: tei

2025-01-03 02:38 UTC, WenjiaoYue commented on comps/rerankings/deployment/docker_compose/rerank_tei.yaml
>      ports:
Yes, I have added this parameter, thanks

2025-01-03 05:17 UTC, closed without merging