[ASR] Fix asr microservice with Python run on SPR CPU
opea-project/GenAIComps pull request #235
Opened 2024-06-23 00:32 UTC by ctao456

## Description

* Fixed Python path dependencies in `asr.py`.
* Added more instructions in `1. Start Microservice with Python (Option 1)` part of `comps/asr/readme.md` to make sure of proper run on Intel® SPR.
* Added expected output printouts in `comps/asr/readme.md`

## Issues

n/a

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

n/a

## Tests

Tested on Intel® SPR CPU to make sure ASR microservice can be run properly.

2024-06-23 02:11 UTC, lvliang-intel approved these changes

2024-06-24 01:34 UTC, Spycsh commented on comps/asr/asr.py
We do not need these two lines. Instead a build from source or explicitly export PYTHONPATH to `comps` is what we need to access the `comps`.

2024-06-24 01:35 UTC, Spycsh requested changes
Edition to README looks good to me. Please remove the change to asr.py.

2024-06-24 02:45 UTC, ctao456 commented on comps/asr/asr.py
I tried build from source according to [Installation - Build from Source
](https://github.com/opea-project/GenAIComps), but the pip package name was `opea-comps` instead of `comps`. So `import comps` results in a `Module not found` error. 
![image](https://github.com/opea-project/GenAIComps/assets/170357112/705ae88c-b32c-4835-9bdf-04baadc63c80)

Do you have inputs on this? Thanks.

2024-06-24 02:54 UTC, Spycsh commented on comps/asr/asr.py
Are you sure you have installed it correctly? I've tested it locally and there should not be a `Module not found` error. Please paste your error log.

2024-06-24 03:10 UTC, Spycsh approved these changes

2024-06-24 03:37 UTC, merged