Update README.md for Multiplatforms
opea-project/GenAIComps pull request #707
Opened 2024-09-18 15:10 UTC by yinghu5

Update README.md for Gaudi & Multiplatforms

## Description

The summary of the proposed changes as long as the relevant motivation and context.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-09-18 15:17 UTC, dbkinder approved these changes
LGTM

2024-09-19 00:11 UTC, mkbhanda requested changes
some minor edits and dropping marketing literature.

2024-09-19 00:11 UTC, mkbhanda commented on comps/llms/text-generation/vllm/ray/README.md
> +This guide provides an example on how to launch vLLM with Ray serve endpoint on [Intel Gaudi2](https://www.intel.com/content/www/us/en/products/details/processors/ai-accelerators/gaudi-overview.html)
```suggestion
This guide provides an example on how to launch vLLM with Ray serve endpoint on [Intel Gaudi2 Accelerator](https://www.intel.com/content/www/us/en/products/details/processors/ai-accelerators/gaudi-overview.html).
```

2024-09-19 00:11 UTC, mkbhanda commented on comps/llms/text-generation/vllm/ray/README.md
>  [vLLM](https://github.com/vllm-project/vllm) is a fast and easy-to-use library for LLM inference and serving, it delivers state-of-the-art serving throughput with a set of advanced features such as P
```suggestion
[vLLM](https://github.com/vllm-project/vllm) is a fast and easy-to-use library for LLM inference and serving, it delivers state-of-the-art serving throughput with a set of advanced features such as PagedAttention and Continuous Batching  among others. Besides GPUs, vLLM supports [Intel CPUs](https://www.intel.com/content/www/us/en/products/overview.html) and [Intel Gaudi accelerators](https://habana.ai/products).
```

2024-09-19 00:11 UTC, mkbhanda commented on comps/llms/text-generation/vllm/ray/README.md
> +[Ray](https://docs.ray.io/en/latest/serve/index.html) is an LLM serving solution that makes it easy to deploy and manage a variety of open source LLMs, built on [Ray Serve](https://docs.ray.io/en/lat
```suggestion
[Ray](https://docs.ray.io/en/latest/serve/index.html) is an LLM serving solution that makes it easy to deploy and manage a variety of open source LLMs. Built on [Ray Serve](https://docs.ray.io/en/latest/serve/index.html) it has native support for autoscaling and multi-node deployments, and is easy to use for LLM inference serving across multiple platforms.
```

2024-09-19 00:43 UTC, mkbhanda approved these changes
LGTM

2024-09-19 00:43 UTC, merged