Add WildGuard Guardrail Microservice
opea-project/GenAIComps pull request #710
Opened 2024-09-19 00:54 UTC by daniel-de-leon-user293

## Description

Add WildGuard to guard against privacy, misinformation, harmful language and malicious use on user input prompts and/or output responses generated by LLMs.

## Issues

n/a
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

n/a

## Tests

- Successfully ran:
   - `guardrails_tgi.py` microservice script directly without container
   - with `docker run` CLI
   - with `docker compose`

2024-09-19 01:37 UTC, letonghan commented
Hi @daniel-de-leon-user293 , please add the test script for WildGuard in `test/guardrails` folder like [this](https://github.com/opea-project/GenAIComps/blob/main/tests/guardrails/test_guardrails_llama_guard_langchain_on_intel_hpu.sh). Name the test script as `test_guardrails_wild_guard_langchain_on_intel_hpu.sh` since you use the hpu version of tgi. 
Thanks : )

2024-09-23 16:09 UTC, qgao007 commented
Hi @daniel-de-leon-user293 , 
Ebi pointed it out to me earlier for my PR, mentioning that the following needs to be added
Also the new Dockerfile introduced by the PR needs to have an entry at:
.github/workflows/docker/compose/guardrails-compose-cd.yaml

2024-09-23 19:18 UTC, daniel-de-leon-user293 commented on comps/guardrails/wildguard/langchain/README.md
> +- Input Guardrails: These are applied to user inputs. An input guardrail can either reject the input, halting further processing.
It is not needed, thanks for catching!

2024-09-27 22:43 UTC, ashahba requested changes
Thanks @daniel-de-leon-user293 for this PR!
I only have a few minor change requests.

2024-09-27 22:43 UTC, ashahba commented on comps/guardrails/wildguard/langchain/README.md
> +curl http://localhost:9090/v1/health_check\
Please leave an space before `\`:
```
curl http://localhost:9090/v1/health_check \
```

2024-09-27 22:43 UTC, ashahba commented on comps/guardrails/wildguard/langchain/README.md
> +curl http://localhost:9090/v1/guardrails\
Same here:
```
curl http://localhost:9090/v1/guardrails \
```

2024-09-27 22:43 UTC, ashahba commented on tests/guardrails/test_guardrails_wild_guard_langchain_on_intel_hpu.sh
> +
Remove this empty line

2024-09-27 22:58 UTC, ashahba approved these changes
LGTM!

2024-10-04 21:33 UTC, dcmiddle commented
@daniel-de-leon-user293 Consider adding documentation or commit message explaining why someone would use wildguard instead of llama guard.

@mkbhanda does OPEA have criteria for when it will accept similar features? 
It's nice to have a variety of options if you know what you are looking for but having to choose among options also detracts from ease of use.

2024-10-05 00:24 UTC, daniel-de-leon-user293 commented
Thank you for your suggestion @dcmiddle. The latest commit adds a bit more description of wild guard in the README. To answer your question,  we’re hoping to provide a diverse set of safety models that users can pick from.

2024-10-06 17:46 UTC, dcmiddle commented
> Thank you for your suggestion @dcmiddle. The latest commit adds a bit more description of wild guard in the README. To answer your question, we’re hoping to provide a diverse set of safety models that users can pick from.

cool. so can this be used in conjunction with llama guard? From the description you added it looks like a complementary list of topics.

2024-10-07 17:05 UTC, daniel-de-leon-user293 commented
No, it can be used in place of Llama Guard. The lists in the README are risk taxonomies that each model was trained to identify according to their respective datasets. Although similar, the models provide different classification performance for difference use cases.

If a user wanted to design an ensemble of guardrails, however, then in that case, these two models could be used in conjunction.

2024-10-09 19:59 UTC, sunstonesecure-robert commented
> It's nice to have a variety of options if you know what you are looking for but having to choose among options also detracts from ease of use.

I'd assert it's *essential* to have a variety of options AND you need to know what you are looking for if you are building LLM apps where security+privacy+bias detection > ease of use

2024-10-11 00:29 UTC, ftian1 approved these changes

2024-10-11 19:10 UTC, merged