Change port.
opea-project/GenAIComps pull request #747
Opened 2024-09-26 08:21 UTC by ZePan110

## Description

Change port.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-09-26 09:15 UTC, letonghan requested changes

2024-09-26 09:15 UTC, letonghan commented on tests/dataprep/test_dataprep_milvus_langchain.sh
>      docker compose up -d
If not get files from milvus, then the docker compose file name is needed to modify as `docker-compose-dataprep-milvus.yaml`.
According to [comps/dataprep/milvus/langchain/docker-compose-dataprep-milvus.yaml](https://github.com/opea-project/GenAIComps/blob/main/comps/dataprep/milvus/langchain/docker-compose-dataprep-milvus.yaml)

2024-09-26 09:18 UTC, letonghan approved these changes
lgtm

2024-09-27 04:16 UTC, chensuyue approved these changes

2024-09-27 04:17 UTC, merged