Add workflow executor strategy
opea-project/GenAIComps pull request #754
Opened 2024-09-30 05:12 UTC by JoshuaL3000

## Description

Add new strategy under agent/src/strategy for workflow executor example

## Issues

RFC: https://github.com/opea-project/docs/pull/77/files

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

2024-09-30 11:49 UTC, lvliang-intel approved these changes

2024-09-30 14:33 UTC, xuechendi commented
@lvliang-intel, @JoshuaL3000 convert this as Draft per Joshua’s request

2024-09-30 16:55 UTC, minmin-intel requested changes
This agent strategy can be realized using the existing react_langgraph or react_llama strategy in the agent component. Each worker agent can be instantiated as a microservice and can be registered as a tool for the supervisor agent in the hierarchical architecture that we currently support. On the other hand, the agent class in this PR will instantiate in total 4 react agents in one microservice, this is not modular. My recommendation is not to add this new strategy. We just need to support custom prompt templates, which is already planned for v1.1 release.

2024-10-04 18:49 UTC, xuechendi commented
@JoshuaL3000 , you might need to add a CICD script in GenAIComps/tests/agent, so we can check on the workflow and output.

2024-10-04 18:55 UTC, xuechendi commented
@JoshuaL3000 , Please add necessary explaination of this strategy, so users know when to use it [comps/agent/langchain/src/strategy/workflowexec/README.md](https://github.com/opea-project/GenAIComps/pull/754/files#diff-71da4f18132bb746c7a27baaea896b2a0945bea49d9a1c9f46568813e617c425)

2024-10-04 18:58 UTC, xuechendi commented
I am a bit lost here, why all nodes - SCHEDULER, STATUS_CHECKER, and DATA_RETRIEVER all needs to call tools?
How are you going to register tools, are they same tools or different?

2024-10-07 06:38 UTC, JoshuaL3000 commented
> @JoshuaL3000 , you might need to add a CICD script in GenAIComps/tests/agent, so we can check on the workflow and output.

2024-10-08 14:54 UTC, xuechendi commented on comps/agent/langchain/src/strategy/workflowexec/planner.py
> +        workflow.add_node("status_checker_tool", tool_node)
tools and status_checker_tool are using same tools, I suggest you either unified all 3 tool_node as 1 or using 3 different name for better workflow control.

2025-03-03 01:51 UTC, joshuayao commented
Hi @JoshuaL3000 @minmin-intel @xuechendi This PR has been open for over 150 days. Shall we continue working on this, or is it no longer a priority?

2025-03-21 02:12 UTC, JoshuaL3000 commented
> Hi @JoshuaL3000 @minmin-intel @xuechendi This PR has been open for over 150 days. Shall we continue working on this, or is it no longer a priority?

Hi, the workflow executor example has been merged to the main branch in another PR. I'll close this PR, thanks.

2025-03-21 02:12 UTC, closed without merging