Add support for Audio and Video summarization to Docsum
opea-project/GenAIComps pull request #865
Opened 2024-11-07 22:55 UTC by MSCetin37

## Description

Extend the current Document Summarization Application by incorporating video and audio summary features. This enhancement will enable the application to summarize video and audio content in addition to text documents, thereby broadening its utility and applicability.

## Issues
https://github.com/opea-project/docs/blob/main/community/rfcs/24-06-21-OPEA-001-DocSum_Video_Audio.md

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Tests

### Whisper Service

Run the following command to validate the Whisper Service:

```bash
python comps/asr/whisper/dependency/check_whisper_server.py 
```

Expected output:

```
{'asr_result': 'who is pat gelsinger'}
```

### Audio2Text Service

Run the following command to validate the Audio2Text Service:

```bash
python comps/dataprep/multimedia2text/audio2text/check_a2t_server.py
```

Expected output:

```
{'downstream_black_list': [], 'id': '21b0459477abea6d85d20f4b5ddcb714', 'query': 'who is pat gelsinger'}
```

*Note: The `id` value will be different.*

### Video2Audio Service

Run the following command to validate the Video2Audio Service:

```bash
python comps/dataprep/multimedia2text/video2audio/check_v2a_microserver.py
```

Expected output:

```
========= Audio file saved as ======
comps/dataprep/multimedia2text/video2audio/converted_audio.wav
====================================
```

### Multimedia2Text Service

Run the following command to validate the Multimedia2Text Service:

```bash
python comps/dataprep/multimedia2text/check_multimedia2text.py 
```

Expected output:

```
Running test: Whisper service
>>> Whisper service Test Passed ... 

Running test: Audio2Text service
>>> Audio2Text service Test Passed ... 

Running test: Video2Text service
>>> Video2Text service Test Passed ... 

Running test: Multimedia2text service
>>> Multimedia2text service test for text data type passed ... 
>>> Multimedia2text service test for audio data type passed ... 
>>> Multimedia2text service test for video data type passed ... 
```

```bash
cd GenAIComps/tests
bash tests/dataprep/test_dataprep_multimedia.sh
```

2024-11-08 07:01 UTC, ashahba requested changes
Thanks @MSCetin37 and @HarshaRamayanam

2024-11-08 07:01 UTC, ashahba commented on comps/dataprep/multimedia2text/video2audio/video2audio_microservice.py
> +import json
Please add copyright header

2024-11-08 07:16 UTC, MSCetin37 commented on comps/asr/whisper/dependency/whisper_model.py
> +        return_timestamps=False,
it is set to false due to Backward Compatibility

2024-11-08 17:24 UTC, ashahba requested changes

2024-11-08 17:24 UTC, ashahba commented on .github/workflows/docker/compose/dataprep-compose-cd.yaml
> +    image: ${REGISTRY:-opea}/dataprep-audio2text:${TAG:-latest}
End of file char missing

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/README.md
> +
Please remove these lines

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/audio2text/Dockerfile
> +ENTRYPOINT ["python", "audio2text.py"]
End of file char missing

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/audio2text/audio2text.py
> +        raise
End of file char missing

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/audio2text/check_a2t_server.py
> +print(response.json())
End of file char missing.
Also print statements are used mostly for debugging.
If this has no use other than debugging, I'd remove it.

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/check_multimedia2text.py
> +        print(f"Test failed: {e}")
End of file char missing.

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/multimedia2text.py
> +        raise
End of file char missing.

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/video2audio/video2audio.py
> +        return base64_str
End of file char missing.

2024-11-08 17:24 UTC, ashahba commented on comps/dataprep/multimedia2text/video2audio/video2audio_microservice.py
> +        raise
End of file char missing.

2024-11-08 21:20 UTC, ashahba approved these changes
LGTM!

2024-11-12 23:25 UTC, mkbhanda approved these changes
LGTM

2024-11-13 00:32 UTC, lvliang-intel commented
@MSCetin37,
please update comps/dataprep/multimedia2text/audio2text/Dockerfile to .github/workflows/docker/compose/dataprep-compose.yaml. The yaml is used for release images build.

2024-11-13 05:51 UTC, merged

2024-11-15 08:35 UTC, lianhao commented
The audio2text service is almost the same as the [asr service](https://github.com/opea-project/GenAIComps/blob/main/comps/asr/whisper/asr.py) except the returned data format. Why can't we combine these 2 services into one?