GraphRAG performance enhacements
opea-project/GenAIComps pull request #924
Opened 2024-11-20 19:44 UTC by rbrugaro

Issue: When property graph store gets filled (~12K nodes, 15K relationships) insertion time in dataprep gets slow. 
Extraction + insertion starts at ~30 sec and once it gets filled grows to (~12K nodes, 15K relationships) ~800 sec
Perf bottleneck this cypher call in llama-index to do node upsert: 
https://github.com/run-llama/llama_index/blob/795bebc2bad31db51b854a5c062bedca42397630/llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py#L334

Performance optimizations in this PR:
1. Move neo4j GraphStore initialization out of detaprep and retrieve function so it's only performed once at the begining
2. Disable schema_refresh of neo4j graph when not necessary because for large graph this is very slow.
3. Switch to OpenAILike class from llama-index to work with vllm or tgi endpoints without code changes (only docker compose.yaml changes)
4. Added concurrency and batching for generating community summaries and generating answers from summaries

2024-12-18 09:57 UTC, eero-t commented
There are lot of dataprep backends and neoj4/llama is not the default one used in docker compose files and Helm charts. 

Do the ones used by default have also similar bottleneck?

2025-01-07 04:23 UTC, rbrugaro commented
> There are lot of dataprep backends and neoj4/llama is not the default one used in docker compose files and Helm charts.
> 
> Do the ones used by default have also similar bottleneck?

@eero-t  thanks for commenting. Althought there are other dataprep backends functionality is very different from this microservice. This dataprep models the microsoft graphRAG (https://github.com/microsoft/graphrag) dataprep backend which performs entity/relationship extraction (using LLM), builds a graph, clusters the graph nodes to generate communities, generates community summaries and those are later retrieved by retriever to answer query by generating a final answer from partial answers. 

For "toy datasets" these bottlenecks are negligible but for large dataset slow down is significant.

2025-01-15 00:54 UTC, ashahba requested changes
Thanks @rbrugaro 
My comments and change requests are mostly generic and feel free to challenge me 😄

2025-01-15 00:54 UTC, ashahba commented on comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py
> +        print(triplets)
could this be `logged` rather than `print`?

2025-01-15 00:54 UTC, ashahba commented on comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py
> +        starttime = time.time()
`starttime` -> `start_time`

2025-01-15 00:54 UTC, ashahba commented on comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py
> +            timeout=1200,  # timeout in seconds)
This is `20` minutes. Is the increase from `10` minutes intentional?

2025-01-15 00:54 UTC, ashahba commented on comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py
> +        # logger.info(f"Total number of triplets {len(index.property_graph_store.get_triplets())}")
Maybe remove this line

2025-01-15 00:54 UTC, ashahba commented on comps/retrievers/neo4j/llama_index/retriever_community_answers_neo4j.py
> +            # logger.info(f" len of triplets {len(self._index.property_graph_store.get_triplets())}")
Remove this line

2025-01-15 00:54 UTC, ashahba commented on comps/retrievers/neo4j/llama_index/retriever_community_answers_neo4j.py
> +        # llm_name = get_attribute_from_tgi_endpoint(TGI_LLM_ENDPOINT, "model_id")
and remove this line

2025-01-15 00:54 UTC, ashahba commented on comps/retrievers/neo4j/llama_index/retriever_community_answers_neo4j.py
> +            timeout=1200,  # timeout in seconds
This one also going from `60` to `1200`. Is that intentional?

2025-01-15 00:54 UTC, ashahba commented on comps/retrievers/neo4j/llama_index/retriever_community_answers_neo4j.py
> +    starttime = time.time()
same with `starttime` to `start_time`

2025-01-15 00:54 UTC, ashahba commented on comps/retrievers/neo4j/llama_index/retriever_community_answers_neo4j.py
> +    start = time.time()
Is this different from `starttime`? Why not use `start` everywhere in the PR?

2025-01-15 00:54 UTC, ashahba commented on tests/retrievers/test_retrievers_neo4j_llama_index_on_intel_hpu.sh
> +    docker pull ghcr.io/huggingface/tgi-gaudi:2.3.1
We may not need the `docker pull` since `docker run` would pull the image. But this is probably everywhere in the repos and should be changed everywhere:

```
$ docker images | grep debian
```
and now if we call `docker run` for the image that doesn't exist:
```
$ docker run --rm -it debian bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
fd0410a2d1ae: Pull complete 
Digest: sha256:321341744acb788e251ebd374aecc1a42d60ce65da7bd4ee9207ff6be6686a62
Status: Downloaded newer image for debian:latest
```

2025-01-15 02:33 UTC, joshuayao commented
Hi @rbrugaro, could you please resolve the comments? Thanks.

2025-01-15 02:34 UTC, lvliang-intel commented on comps/dataprep/neo4j/llama_index/config.py
> +LLM_MODEL_ID = os.getenv("LLM_MODEL_ID", "meta-llama/Meta-Llama-3.1-70B-Instruct")
Could we use a smaller model in this case? A 70B model seems too large for typical users.

2025-01-15 03:52 UTC, xiguiw commented
> Issue: When property graph store gets filled (~12K nodes, 15K relationships) insertion time in dataprep gets slow. Extraction + insertion starts at ~30 sec and once it gets filled grows to (~12K nodes, 15K relationships) ~800 sec Perf bottleneck this cypher call in llama-index to do node upsert: https://github.com/run-llama/llama_index/blob/795bebc2bad31db51b854a5c062bedca42397630/llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py#L334
> 
> WIP solution:
> 
> 1. mode initialization out of detaprep and retrieve function so only performed once
> 2. ...

Do you mean the mode initialization of TGI/TEI service? If yes, I suppose the LLM model initialization are in TGI/TEI service, so model initialization should be performed only once. Both dataprep and retrieval only refer to the service instead of creating a local one.
The dependency should be in document and docker-compose.yml file. 

Does GraphRAG enabled in ChatQnA? the dataprep (GraphRAG) share the same TGI/TEI service (docker container) with ChatQnA LLM?

2025-01-15 03:53 UTC, xiguiw commented on comps/dataprep/neo4j/llama_index/config.py
>  OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
1. Either TGI or OpenAI LLM are used to create graph in the code. 
    But we could not get this information from the configure file and document. Could you update this in document or point me the link if I missed this info.
     If both OPEN_AI_KEY and TGI are set, OpenAI Model is of the high priority (if branch). Could we switch the priority, of OpenAI and Gaudi TGI if we prefer to recommend user trying Gaudi?

2025-01-15 04:22 UTC, rbrugaro commented on comps/dataprep/neo4j/llama_index/config.py
> +LLM_MODEL_ID = os.getenv("LLM_MODEL_ID", "meta-llama/Meta-Llama-3.1-70B-Instruct")
The CI test scrip actually sets the LLM_MODEL_ID to an 8B model but in reality for extracting a good quality graph (entities and relationships out of documents) a larger model is needed.

2025-01-15 04:29 UTC, rbrugaro commented on comps/dataprep/neo4j/llama_index/config.py
>  OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GraphRAG quality depends heavily on the quality of the extracted graph (nodes and relationships extracted from the text). This implementation is based on microsoft graphrag and they used gpt-4. https://arxiv.org/html/2404.16130v1
I think ideally gpt4-like model is used for dataprep which is a one time thing, and then for 1)generating graph community summaries, 2)generating per community query answers and3) generating final answer a smaller llm is used in gaudi. Currently all generations make request to a single llm endpoint openai or tgi/vllm (it actually works with both).

2025-01-15 04:47 UTC, rbrugaro commented
> > Issue: When property graph store gets filled (~12K nodes, 15K relationships) insertion time in dataprep gets slow. Extraction + insertion starts at ~30 sec and once it gets filled grows to (~12K nodes, 15K relationships) ~800 sec Perf bottleneck this cypher call in llama-index to do node upsert: https://github.com/run-llama/llama_index/blob/795bebc2bad31db51b854a5c062bedca42397630/llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py#L334
> > WIP solution:
> > 
> > 1. mode initialization out of detaprep and retrieve function so only performed once
> > 2. ...
> 
> Do you mean the mode initialization of TGI/TEI service? If yes, I suppose the LLM model initialization are in TGI/TEI service, so model initialization should be performed only once. Both dataprep and retrieval only refer to the service instead of creating a local one. The dependency should be in document and docker-compose.yml file.
> 
> Does GraphRAG enabled in ChatQnA? the dataprep (GraphRAG) share the same TGI/TEI service (docker container) with ChatQnA LLM?

@xiguiw sorry for the confusion and thx for the comments. I updated the PR description maybe is clearer now. I was referring to the initialization of the GraphStore. The inference microservices are just deployed and initialized once. dataprep and retriever code just send endpoint requests to those with llama-index api. 
I am not sure what you mean by GraphRAG and ChatQnA sharing same docker containers. This yaml defines the deployment: https://github.com/rbrugaro/GenAIComps/blob/GRAG_1.2/comps/dataprep/neo4j/llama_index/neo4j_llama_index.yaml

2025-01-15 05:25 UTC, lkk12014402 approved these changes
LGTM

2025-01-15 05:26 UTC, rbrugaro commented on comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py
> +            timeout=1200,  # timeout in seconds)
if i recall correctly i changed because I hit timeout while running long experiments w 405B model. emb increase not intended.

2025-01-15 05:34 UTC, rbrugaro commented on tests/retrievers/test_retrievers_neo4j_llama_index_on_intel_hpu.sh
> +    docker pull ghcr.io/huggingface/tgi-gaudi:2.3.1
@ashahba sorry, not sure how you want me to change?

2025-01-16 23:47 UTC, rbrugaro commented on tests/retrievers/test_retrievers_neo4j_llama_index_on_intel_hpu.sh
> +    docker pull ghcr.io/huggingface/tgi-gaudi:2.3.1
I will leave as is then

2025-01-16 23:47 UTC, rbrugaro commented on comps/dataprep/neo4j/llama_index/config.py
> +LLM_MODEL_ID = os.getenv("LLM_MODEL_ID", "meta-llama/Meta-Llama-3.1-70B-Instruct")
changed

2025-01-17 02:45 UTC, letonghan requested changes

2025-01-17 02:45 UTC, letonghan commented on comps/retrievers/src/integrations/neo4j.py
> +    async def invoke(self, input: Union[ChatCompletionRequest]) -> Union[ChatCompletionRequest]:
Please keep return `list` type. The output format will be processed in `opea_retrievers_microservice.py`.

2025-01-17 10:33 UTC, letonghan approved these changes
lgtm

2025-01-19 13:00 UTC, merged