Migration Suggestion
opea-project/GenAIComps pull request #959
Opened 2024-12-02 04:41 UTC by yongfengdu

The directory layout suggest for helm charts in GenAIComps

## Description

The summary of the proposed changes as long as the relevant motivation and context.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-12-02 17:55 UTC, eero-t requested changes

2024-12-02 17:55 UTC, eero-t commented on helm-charts/llm-uservice/README.md
> +| global.monitoring               | bool   | `false`          | Service usage metrics           |
Helm install fails if user enables this without reading the docs first => Just removing link to doc is not a solution!

Neither is duplicating the docs in multiple repos.

=> IMHO best would be to move common Helm chart docs (on HPA, monitoring etc) to `helm-charts` dir here, and link it also from relevant Helm chart READMEs in Examples repo.

2024-12-02 18:00 UTC, eero-t commented
As to other CI failures...  Clearly pre-CI `check-yaml` checks in this repo will need to be updated to handle Helm charts.

2024-12-03 02:42 UTC, yongfengdu commented
@eero-t Thanks. This is just a PR draft created to show possible dir layout, doesn't mean the final decision. So, many issues are not resolved yet.

2024-12-11 08:09 UTC, closed without merging